<?php
$pagename='Master-Employee';
include 'header.php';

if(isset($_POST['save']) && $_POST['save']=='Save')
{
	$emp_no		= mysqli_real_escape_string($conn, trim(addslashes($_POST['emp_no'])));
	$emp_name	= mysqli_real_escape_string($conn, trim(addslashes($_POST['emp_name'])));
	$mail		= mysqli_real_escape_string($conn, trim(addslashes($_POST['mail'])));
	$mobile		= mysqli_real_escape_string($conn, trim(addslashes($_POST['mobile'])));
	$doj		= mysqli_real_escape_string($conn, trim(addslashes($_POST['doj'])));
	
	$count=mysqli_num_rows(mysqli_query($conn,'select * from emp_master where emp_no = \''.$emp_no.'\''));
	if($count=='0')
	{
		$insert=mysqli_query($conn,'INSERT INTO emp_master SET
								emp_no		=	\''.$emp_no.'\',
								emp_name	=	\''.$emp_name.'\',
								mail		=	\''.$mail.'\',
								mobile		=	\''.$mobile.'\',
								doj			=	\''.$doj.'\',
								dol			=	\'9999-12-31\',
								created_by	=	\''.$_SESSION['emp_no'].'\'');	
		
		$alpha	= str_shuffle('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz');
		$numeric= str_shuffle('0123456789');
		$special= str_shuffle('#@&');
		$code	= substr($alpha, 0, 5).substr($special, 0, 1) . substr($numeric, 0, 2);
		$num 	= str_shuffle($code);
		 
		$spw="aes_encrypt('$num','digital.login')";					
		$insert1=mysqli_query($conn,'INSERT INTO login set emp_no=\''.$emp_no.'\',password='.$spw.'');
		
		if($mail!='')
		{
			$to =$mail; 
				
			$subject = "LOGIN CREDENTIALS FOR DIGITAL INSPECTION PORTAL";
			
			$link='https://'.$_SERVER['HTTP_HOST'].'/digital_quality'; 
			
			$msg="<html><body><p>Dear ".$_POST['emp_name'].",<br><br>We are happy to inform you that your login has been created.<br><br>Please note the login credentials:<br><br><a href='".$link."' target='_blank'>".$link."</a> <br> User Id : <b>".$emp_no."</b><br>password : <b>".$num."</b><br><br> <b style='color:red'>Note - Its Autogenerated email, do not reply to this email id.</b></body></html>";
			
			$headers .= "MIME-Version: 1.0" . "\r\n";
		
			$headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";

			$headers .= 'From: <digital@wheelsindia.com>' . "\r\n";
			 
			$send=mail($to,$subject,$msg,$headers);
		}
		
		echo "<script type=\"text/javascript\">alert(\"Employee created successfully\"); window.location = \"employee_view.php\"</script>";
	}
	else
	{
		echo "<script type=\"text/javascript\">alert(\"Employee already exists\");window.location = \"employee_add.php\"</script>";
		die;
	}
}

?>
<script>
function ValidateAlpha(evt)
{
	var keyCode = (evt.which) ? evt.which : evt.keyCode
	if ((keyCode < 65 || keyCode > 90) && (keyCode < 97 || keyCode > 123) && keyCode != 32)
	return false;

	return true;
}



function isNumberKey(evt)
{
	var charCode = (evt.which) ? evt.which : evt.keyCode				
	if (charCode != 46 && charCode != 45 && charCode > 31 && (charCode < 48 || charCode > 57))
	return false;

	return true;
}
</script>

<div class="container-fluid">
	<h1 class="h3 mb-4 text-gray-800">Employee Master - ADD</h1>
	<div class="card shadow mb-4">
		 <div class="card-body">
			<div class='col-md-12' align='right' style='margin:10px;'>
				<a href='employee_view.php' class='btn btn-primary'>View Employee</a>
			</div>
			<form name='employee' id='employee' action='' method='post'>
				<div class="form-group row">
					<label for="inputPassword" class="col-sm-2 col-form-label">Employee No.</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="emp_no" id="emp_no"  maxlength='8' onpaste="return false;"  placeholder="Employee Number"  onkeypress="return isNumberKey(event)"  required>
					</div>
				</div>
				
				<div class="form-group row">
					<label for="inputPassword" class="col-sm-2 col-form-label">Employee Name</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="emp_name" id="emp_name"  onpaste="return false;" placeholder="Employee Name" onKeyPress="return ValidateAlpha(event);" required>
					</div>
				</div>
				
				<div class="form-group row">
					<label for="inputPassword" class="col-sm-2 col-form-label">Email</label>
					<div class="col-sm-10">
						<input type="email" class="form-control" name="mail" id="mail"  placeholder="Employee Email"  required>
					</div>
				</div>
				
				<div class="form-group row">
					<label for="inputPassword" class="col-sm-2 col-form-label">Mobile</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="mobile" id="mobile" maxlength='10' onpaste="return false;"  placeholder="Employee Mobile"  onkeypress="return isNumberKey(event)"  required>
					</div>
				</div>
				
				<div class="form-group row">
					<label for="inputPassword" class="col-sm-2 col-form-label">DOJ</label>
					<div class="col-sm-10">
						<input type="date" class="form-control" name="doj" id="doj" required>
					</div>
				</div>
				
				 
				
				 
				
				<div class="form-group row">
					<div class="col-sm-12" align="center">
						<input type="submit" class="btn btn-primary" name="save" id="save" value='Save' >
					</div>
				</div>
				
				
			</form>
		</div>
	</div>
</div>
<?php
include 'footer.php';
?>